"""traffic model

Revision ID: 56001dbb442e
Revises: cd4c37ebabe2
Create Date: 2022-04-16 23:52:52.021117

"""
import uuid

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '56001dbb442e'
down_revision = 'cd4c37ebabe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traffic_record',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('date_from', sa.Integer(), nullable=False),
                    sa.Column('date_to', sa.Integer(), nullable=False),
                    sa.Column('provider_id', sa.String(), nullable=False),
                    sa.Column('quantity_bytes', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('idx_from_to', 'traffic_record', ['date_from', 'date_to'], unique=False)
    op.execute("ALTER TABLE provider ADD COLUMN external_id VARCHAR NOT NULL DEFAULT ''")
    op.execute("UPDATE provider SET external_id = substr(payload,20,36) WHERE type='openvpn'")
    op.create_index(op.f('ix_provider_external_id'), 'provider', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_external_id'), table_name='provider')
    op.drop_column('provider', 'external_id')
    op.drop_index('idx_from_to', table_name='traffic_record')
    op.drop_table('traffic_record')
    # ### end Alembic commands ###
