version: '3'
services:
  nginx:
    image: nginx:1.21.6-alpine
    network_mode: "host"
    # ports:
    #     - 5000:5000
    volumes:
      - ./self-signed.conf:/etc/nginx/snippets/self-signed.conf
      - ./nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
      - ./ssl-params.conf:/etc/nginx/snippets/ssl-params.conf
      - ./dhparam.pem:/etc/ssl/certs/dhparam.pem
      - ./default:/etc/nginx/conf.d/default.conf
      - ./www:/var/www
      - ./logs/nginx:/var/log/nginx