name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8 ]
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install sqlite3
        run: |
          wget -c https://www.sqlite.org/2022/sqlite-tools-linux-x86-3380500.zip
          tar xvfz sqlite-tools-linux-x86-3380500.zip
          sudo cp sqlite-tools-linux-x86-3380500/* /usr/bin/
      - name: Check sqlite version
        run: |
          sqlite3 --version
      - name: Switch to Current Branch
        run: git checkout ${{ env.BRANCH }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run unit tests
        run: |
          chmod +x run_tests.sh
          ./run_tests.sh
